// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: options/options.proto

package options

import (
	descriptor "github.com/golang/protobuf/protoc-gen-go/descriptor"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GqlInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Param         string                 `protobuf:"bytes,50031,opt,name=param,proto3" json:"param,omitempty"`
	Type          string                 `protobuf:"bytes,50032,opt,name=type,proto3" json:"type,omitempty"`
	Optional      bool                   `protobuf:"varint,50033,opt,name=optional,proto3" json:"optional,omitempty"`
	Primitive     bool                   `protobuf:"varint,50034,opt,name=primitive,proto3" json:"primitive,omitempty"`
	Array         bool                   `protobuf:"varint,50035,opt,name=array,proto3" json:"array,omitempty"`
	Empty         bool                   `protobuf:"varint,50036,opt,name=empty,proto3" json:"empty,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GqlInput) Reset() {
	*x = GqlInput{}
	mi := &file_options_options_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GqlInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GqlInput) ProtoMessage() {}

func (x *GqlInput) ProtoReflect() protoreflect.Message {
	mi := &file_options_options_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GqlInput.ProtoReflect.Descriptor instead.
func (*GqlInput) Descriptor() ([]byte, []int) {
	return file_options_options_proto_rawDescGZIP(), []int{0}
}

func (x *GqlInput) GetParam() string {
	if x != nil {
		return x.Param
	}
	return ""
}

func (x *GqlInput) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *GqlInput) GetOptional() bool {
	if x != nil {
		return x.Optional
	}
	return false
}

func (x *GqlInput) GetPrimitive() bool {
	if x != nil {
		return x.Primitive
	}
	return false
}

func (x *GqlInput) GetArray() bool {
	if x != nil {
		return x.Array
	}
	return false
}

func (x *GqlInput) GetEmpty() bool {
	if x != nil {
		return x.Empty
	}
	return false
}

type MethodOptions struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Kind          string                 `protobuf:"bytes,50001,opt,name=kind,proto3" json:"kind,omitempty"`
	Target        string                 `protobuf:"bytes,50002,opt,name=target,proto3" json:"target,omitempty"` // e.g., "admin", "client", "internal", "all"
	GqlInput      *GqlInput              `protobuf:"bytes,50003,opt,name=gql_input,json=gqlInput,proto3" json:"gql_input,omitempty"`
	GqlOutput     string                 `protobuf:"bytes,50004,opt,name=gql_output,json=gqlOutput,proto3" json:"gql_output,omitempty"`
	Skip          bool                   `protobuf:"varint,50005,opt,name=skip,proto3" json:"skip,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MethodOptions) Reset() {
	*x = MethodOptions{}
	mi := &file_options_options_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MethodOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MethodOptions) ProtoMessage() {}

func (x *MethodOptions) ProtoReflect() protoreflect.Message {
	mi := &file_options_options_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MethodOptions.ProtoReflect.Descriptor instead.
func (*MethodOptions) Descriptor() ([]byte, []int) {
	return file_options_options_proto_rawDescGZIP(), []int{1}
}

func (x *MethodOptions) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *MethodOptions) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

func (x *MethodOptions) GetGqlInput() *GqlInput {
	if x != nil {
		return x.GqlInput
	}
	return nil
}

func (x *MethodOptions) GetGqlOutput() string {
	if x != nil {
		return x.GqlOutput
	}
	return ""
}

func (x *MethodOptions) GetSkip() bool {
	if x != nil {
		return x.Skip
	}
	return false
}

var file_options_options_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptor.MethodOptions)(nil),
		ExtensionType: (*MethodOptions)(nil),
		Field:         50000,
		Name:          "dieture.method",
		Tag:           "bytes,50000,opt,name=method",
		Filename:      "options/options.proto",
	},
	{
		ExtendedType:  (*descriptor.MessageOptions)(nil),
		ExtensionType: (*bool)(nil),
		Field:         50011,
		Name:          "dieture.skip",
		Tag:           "varint,50011,opt,name=skip",
		Filename:      "options/options.proto",
	},
	{
		ExtendedType:  (*descriptor.FieldOptions)(nil),
		ExtensionType: (*bool)(nil),
		Field:         50021,
		Name:          "dieture.required",
		Tag:           "varint,50021,opt,name=required",
		Filename:      "options/options.proto",
	},
	{
		ExtendedType:  (*descriptor.FieldOptions)(nil),
		ExtensionType: (*bool)(nil),
		Field:         50022,
		Name:          "dieture.keep_case",
		Tag:           "varint,50022,opt,name=keep_case",
		Filename:      "options/options.proto",
	},
}

// Extension fields to descriptor.MethodOptions.
var (
	// optional dieture.MethodOptions method = 50000;
	E_Method = &file_options_options_proto_extTypes[0]
)

// Extension fields to descriptor.MessageOptions.
var (
	// optional bool skip = 50011;
	E_Skip = &file_options_options_proto_extTypes[1]
)

// Extension fields to descriptor.FieldOptions.
var (
	// optional bool required = 50021;
	E_Required = &file_options_options_proto_extTypes[2]
	// optional bool keep_case = 50022;
	E_KeepCase = &file_options_options_proto_extTypes[3]
)

var File_options_options_proto protoreflect.FileDescriptor

const file_options_options_proto_rawDesc = "" +
	"\n" +
	"\x15options/options.proto\x12\adieture\x1a google/protobuf/descriptor.proto\"\xa6\x01\n" +
	"\bGqlInput\x12\x16\n" +
	"\x05param\x18\xef\x86\x03 \x01(\tR\x05param\x12\x14\n" +
	"\x04type\x18\xf0\x86\x03 \x01(\tR\x04type\x12\x1c\n" +
	"\boptional\x18\xf1\x86\x03 \x01(\bR\boptional\x12\x1e\n" +
	"\tprimitive\x18\xf2\x86\x03 \x01(\bR\tprimitive\x12\x16\n" +
	"\x05array\x18\xf3\x86\x03 \x01(\bR\x05array\x12\x16\n" +
	"\x05empty\x18\xf4\x86\x03 \x01(\bR\x05empty\"\xa8\x01\n" +
	"\rMethodOptions\x12\x14\n" +
	"\x04kind\x18ц\x03 \x01(\tR\x04kind\x12\x18\n" +
	"\x06target\x18҆\x03 \x01(\tR\x06target\x120\n" +
	"\tgql_input\x18ӆ\x03 \x01(\v2\x11.dieture.GqlInputR\bgqlInput\x12\x1f\n" +
	"\n" +
	"gql_output\x18Ԇ\x03 \x01(\tR\tgqlOutput\x12\x14\n" +
	"\x04skip\x18Ն\x03 \x01(\bR\x04skip:P\n" +
	"\x06method\x12\x1e.google.protobuf.MethodOptions\x18І\x03 \x01(\v2\x16.dieture.MethodOptionsR\x06method:5\n" +
	"\x04skip\x12\x1f.google.protobuf.MessageOptions\x18ۆ\x03 \x01(\bR\x04skip:>\n" +
	"\brequired\x12\x1d.google.protobuf.FieldOptions\x18\xe5\x86\x03 \x01(\bR\brequired\x88\x01\x01:?\n" +
	"\tkeep_case\x12\x1d.google.protobuf.FieldOptions\x18\xe6\x86\x03 \x01(\bR\bkeepCase\x88\x01\x01B\n" +
	"Z\b/optionsb\x06proto3"

var (
	file_options_options_proto_rawDescOnce sync.Once
	file_options_options_proto_rawDescData []byte
)

func file_options_options_proto_rawDescGZIP() []byte {
	file_options_options_proto_rawDescOnce.Do(func() {
		file_options_options_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_options_options_proto_rawDesc), len(file_options_options_proto_rawDesc)))
	})
	return file_options_options_proto_rawDescData
}

var file_options_options_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_options_options_proto_goTypes = []any{
	(*GqlInput)(nil),                  // 0: dieture.GqlInput
	(*MethodOptions)(nil),             // 1: dieture.MethodOptions
	(*descriptor.MethodOptions)(nil),  // 2: google.protobuf.MethodOptions
	(*descriptor.MessageOptions)(nil), // 3: google.protobuf.MessageOptions
	(*descriptor.FieldOptions)(nil),   // 4: google.protobuf.FieldOptions
}
var file_options_options_proto_depIdxs = []int32{
	0, // 0: dieture.MethodOptions.gql_input:type_name -> dieture.GqlInput
	2, // 1: dieture.method:extendee -> google.protobuf.MethodOptions
	3, // 2: dieture.skip:extendee -> google.protobuf.MessageOptions
	4, // 3: dieture.required:extendee -> google.protobuf.FieldOptions
	4, // 4: dieture.keep_case:extendee -> google.protobuf.FieldOptions
	1, // 5: dieture.method:type_name -> dieture.MethodOptions
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	5, // [5:6] is the sub-list for extension type_name
	1, // [1:5] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_options_options_proto_init() }
func file_options_options_proto_init() {
	if File_options_options_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_options_options_proto_rawDesc), len(file_options_options_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 4,
			NumServices:   0,
		},
		GoTypes:           file_options_options_proto_goTypes,
		DependencyIndexes: file_options_options_proto_depIdxs,
		MessageInfos:      file_options_options_proto_msgTypes,
		ExtensionInfos:    file_options_options_proto_extTypes,
	}.Build()
	File_options_options_proto = out.File
	file_options_options_proto_goTypes = nil
	file_options_options_proto_depIdxs = nil
}
